; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32c3_supermini]
platform = https://github.com/pioarduino/platform-espressif32.git#55.03.39
board = esp32-c3-devkitm-1
board_build.partitions = custom_partitions.csv
extra_scripts = pre:scripts/generate_headers.py
board_build.f_cpu = 160000000L
framework = arduino
build_flags=
	-DVERSION_MAJOR=2
	-DVERSION_MINOR=1
	-DWEBAPPVER_MAJOR=2
	-DWEBAPPVER_MINOR=0
	-DCORE_DEBUG_LEVEL=0
	-DGITHUBAPIHOST='"api.github.com"'
	-DGITHUBTOKEN='""'
	-DGITHUBREPOPATH='"/repos/gadec-uk/tiny-departures-board/releases/latest"'
  	-DARDUINO_USB_MODE=1
  	-DARDUINO_USB_CDC_ON_BOOT=1
	-DU8G2_WITHOUT_FONT_ROTATION
	-DU8G2_WITHOUT_UNICODE

monitor_speed = 115200
lib_deps =
	tzapu/WiFiManager@2.0.17
	olikraus/U8g2@2.36.5
	bblanchon/ArduinoJson@7.2.2
  	ESP32Async/AsyncTCP@3.4.10
  	ESP32Async/ESPAsyncWebServer@3.10.0